# To make an environment:
#
#   $ conda env create -f conda_env.yml
#
# To update an environment with changes in the yml file:
#
#   $ conda activate autolabel
#   $ conda env update -f conda_env.yml

name: autolabel

channels:
  - defaults
  - anaconda
  - intel

dependencies:
  - python=3
  - numpy
  - matplotlib
  - scipy
  - pillow
  - tqdm
  - xmltodict
  - opencv
